name: catatan_keuangan
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  date_time_picker: ^2.1.0
  intl: ^0.17.0
  # intl: ^0.18.1 not supported with date_time_picker: ^2.1.0

  # firebase
  firebase_core: ^2.22.0
  firebase_auth: ^4.14.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
  fonts:
    - family: Poppins-bold
      fonts:
        - asset: fonts/Poppins-Bold.ttf
    - family: Poppins-semiBold
      fonts:
        - asset: fonts/Poppins-SemiBold.ttf
    - family: Poppins-regular
      fonts:
        - asset: fonts/Poppins-Regular.ttf
